### ISSUE TITLE
Yougov specific excuse

### ISSUE THREAD

**Issue by tabo** [pmxbot/excuses#1]
I randomed a Yougov excuse today.

> "There was an infinite loop in the QSL that sent half the respondents through Brandindex an infinite number of times."

Introduced in 6888ab095505966885fefc89045c06d3ca845842

Perhaps it's time to have separate excuse files?

**Comment by jaraco** [comment]
Meh. Probably not worth the effort to make extensible... Did you encounter this in usage outside YouGov? That makes me happy ;)

I've thought about this "excuse" from an outsider's perspective and my feeling was that although it's not directly meaningful to non-YouGov users, it's still technobabbly enough to be entertaining.

It could be adapted to be more generic. s/QSL/script/ s/Brandindex/our system/ and maybe s/respondents/users/.

I'm open to suggestions too. Feel free to send a PR.

**Comment by palmcal** [comment]
Funny.  Is being routed to BrandIndex a bad thing?

On Sat, Apr 23, 2016 at 9:46 AM, Jason R. Coombs notifications@github.com
wrote:

> Meh. Probably not worth the effort to make extensible... Did you encounter
> this in usage outside YouGov? That makes me happy ;)
> 
> I've thought about this "excuse" from an outsider's perspective and my
> feeling was that although it's not directly meaningful to non-YouGov users,
> it's still technobabbly enough to be entertaining.
> 
> It could be adapted to be more generic. s/QSL/script/ s/Brandindex/our
> system/ and maybe s/respondents/users/.
> 
> I'm open to suggestions too. Feel free to send a PR.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/yougov/excuses/issues/1#issuecomment-213778385

## 

Brad Palmquist
brad.palmquist@gmail.com

**Comment by tabo** [comment]
@jaraco: fair enough. And yeah it was at Twitch :)

@palmcal I guess it's bad to be routed through Brandindex an infinite number of times!
